/** 登录 */
export const LOG_IN = 'LOG_IN';
export const LOG_IN_ERROR = 'LOG_IN_ERROR';
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';

/** 清除用户信息 */
export const CLEAR_USER_INFO = 'CLEAR_USER_INFO';

/** 发送短信验证码 */
export const SEND_CODE = 'SEND_CODE';
export const SEND_CODE_ERROR = 'SEND_CODE_ERROR';
export const SEND_CODE_SUCCESS = 'SEND_CODE_SUCCESS';

/** 通过openId获取用户信息 */
export const GET_USER_INFO_BY_OPENID = 'GET_USER_INFO_BY_OPENID';
export const GET_USER_INFO_BY_OPENID_ERROR = 'GET_USER_INFO_BY_OPENID_ERROR';
export const GET_USER_INFO_BY_OPENID_SUCCESS = 'GET_USER_INFO_BY_OPENID_SUCCESS';

/** 获取车主认证状态 */
export const GET_CAR_VERIFY_STATUS = 'GET_CAR_VERIFY_STATUS';
export const GET_CAR_VERIFY_STATUS_ERROR = 'GET_CAR_VERIFY_STATUS_ERROR';
export const GET_CAR_VERIFY_STATUS_SUCCESS = 'GET_CAR_VERIFY_STATUS_SUCCESS';
