
/** 获取电桩列表 */
export const GET_PILE_LIST = 'GET_PILE_LIST'
export const GET_PILE_LIST_SUCCESS = 'GET_PILE_LIST_SUCCESS'
export const GET_PILE_LIST_ERROR = 'GET_PILE_LIST_ERROR'

/** 获取电桩详情 */
export const GET_PILE_DETAILS = 'GET_PILE_DETAILS'
export const GET_PILE_DETAILS_SUCCESS = 'GET_PILE_DETAILS_SUCCESS'
export const GET_PILE_DETAILS_ERROR = 'GET_PILE_DETAILS_ERROR'