/** 获取钱包详情 */
export const GET_WALLET_DETAILS = 'GET_WALLET_DETAILS';
export const GET_WALLET_DETAILS_SUCCESS = 'GET_WALLET_DETAILS_SUCCESS';
export const GET_WALLET_DETAILS_ERROR = 'GET_WALLET_DETAILS_ERROR';