/** 获取站点列表 */
export const GET_STATION_LIST = 'GET_STATION_LIST'
export const GET_STATION_LIST_SUCCESS = 'GET_STATION_LIST_SUCCESS'

/** 获取站点详情 */
export const GET_STATION_DETAILS = 'GET_STATION_DETAILS'
export const GET_STATION_DETAILS_SUCCESS = 'GET_STATION_DETAILS_SUCCESS'

/** 获取站点计费规则 */
export const GET_STATION_RULES = 'GET_STATION_RULES'
export const GET_STATION_RULES_SUCCESS = 'GET_STATION_RULES_SUCCESS'