/** 启动充电 */
export const APPLY_CHARGE = 'APPLY_CHARGE';
export const APPLY_CHARGE_ERROR = 'APPLY_CHARGE_ERROR';
export const APPLY_CHARGE_SUCCESS = 'APPLY_CHARGE_SUCCESS';

/** 获取充电信息 */
export const GET_CHARGE_INFO = 'GET_CHARGE_INFO';
export const GET_CHARGE_INFO_ERROR = 'GET_CHARGE_INFO_ERROR';
export const GET_CHARGE_INFO_SUCCESS = 'GET_CHARGE_INFO_SUCCESS';

export const CLEAR_APPLY_CHARGE_TIMER = 'CLEAR_APPLY_CHARGE_TIMER';