/** 获取订单列表 */
export const GET_ORDER_LIST = 'GET_ORDER_LIST';
export const GET_ORDER_LIST_ERROR = 'GET_ORDER_LIST_ERROR';
export const GET_ORDER_LIST_SUCCESS = 'GET_ORDER_LIST_SUCCESS';

/** 获取订单详情 */
export const GET_ORDER_DETAILS = 'GET_ORDER_DETAILS';
export const GET_ORDER_DETAILS_ERROR = 'GET_ORDER_DETAILS_ERROR';
export const GET_ORDER_DETAILS_SUCCESS = 'GET_ORDER_DETAILS_SUCCESS';